import {
  IconAdjustments,
  IconArchive,
  IconBell,
  IconBox,
  IconBuildingStore,
  IconCashBanknote,
  IconCategory,
  IconChartBar,
  IconClipboardList,
  IconCreditCard,
  IconDatabase,
  IconFileAnalytics,
  IconFileText,
  IconHeartbeat,
  IconKey,
  IconLayoutDashboard,
  IconLifebuoy,
  IconMessage,
  IconPackage,
  IconPhoto,
  IconRobot,
  IconSettings,
  IconShieldCheck,
  IconShoppingBag,
  IconShoppingCart,
  IconSlideshow,
  IconTruck,
  IconUsers,
  IconUsersGroup,
  IconWorld,
} from '@tabler/icons-react'

export function getLanguage() {
  return document.getElementById('admin-react-shell')?.getAttribute('data-current-lang') || 'ar'
}

const sectionTranslations = {
  ar: {
    overview: 'نظرة عامة',
    sales: 'المبيعات',
    catalog: 'المتجر والمنتجات',
    people: 'الفريق والموظفون',
    content: 'المحتوى',
    finance: 'الفوترة',
    automation: 'الأتمتة والذكاء',
    system: 'النظام',
  },
  fr: {
    overview: 'Vue d’ensemble',
    sales: 'Ventes',
    catalog: 'Boutique & Produits',
    people: 'Équipe & Personnel',
    content: 'Contenu',
    finance: 'Facturation',
    automation: 'Automatisation & IA',
    system: 'Système',
  },
  en: {
    overview: 'Overview',
    sales: 'Sales',
    catalog: 'Store & Products',
    people: 'Team & Staff',
    content: 'Content',
    finance: 'Billing',
    automation: 'Automation & AI',
    system: 'System',
  }
}

const pageNameTranslations = {
  ar: {
    'index.php': 'لوحة الإدارة',
    'store.php': 'المتجر',
    'store-dashboard.php': 'لوحة المتجر',
    'settings.php': 'إعدادات المتجر',
    'profile-edit.php': 'الملف الشخصي',
    'site-security.php': 'أمان الموقع',
    'system-health.php': 'صحة النظام',
    'integrations.php': 'التكاملات',
    'performance-settings.php': 'إعدادات الأداء',
    'users.php': 'المستخدمون',
    'product.php': 'المنتجات',
    'product-add.php': 'إضافة منتج',
    'product-edit.php': 'تعديل منتج',
    'size.php': 'المقاسات',
    'size-add.php': 'إضافة مقاس',
    'size-edit.php': 'تعديل مقاس',
    'color.php': 'الألوان',
    'country.php': 'الولايات والدول',
    'shipping-cost.php': 'تكاليف التوصيل',
    'delivery_list.php': 'قائمة التوصيل',
    'delivery-company.php': 'شركات التوصيل',
    'order.php': 'الطلبات',
    'order-statistics.php': 'إحصائيات الطلبات',
    'order-details.php': 'تفاصيل الطلب',
    'incomplete-orders.php': 'الطلبات غير المكتملة',
    'ecotrack-diagnostics.php': 'تشخيص Ecotrack',
    'customer.php': 'العملاء',
    'customer-message.php': 'رسائل العملاء',
    'slider.php': 'السلايدر',
    'slider-add.php': 'إضافة سلايدر',
    'slider-edit.php': 'تعديل سلايدر',
    'service.php': 'الخدمات',
    'service-add.php': 'إضافة خدمة',
    'service-edit.php': 'تعديل خدمة',
    'faq.php': 'الأسئلة الشائعة',
    'page.php': 'الصفحات',
    'photo.php': 'المعرض',
    'photo-add.php': 'إضافة صورة',
    'photo-edit.php': 'تعديل صورة',
    'social-media.php': 'وسائل التواصل',
    'top-category.php': 'الفئات الرئيسية',
    'mid-category.php': 'الفئات الفرعية',
    'end-category.php': 'الفئات النهائية',
    'billing.php': 'الفوترة',
    'commission-settings.php': 'العمولات',
    'disaster-recovery.php': 'التعافي من الكوارث',
    'queue-dashboard.php': 'الطوابير',
    'audit-log.php': 'سجل التدقيق',
    'api-keys.php': 'مفاتيح API',
    'backups.php': 'النسخ الاحتياطي',
    'pixel.php': 'بكسلات التتبع',
    'pixel-add.php': 'إضافة بكسل',
    'pixel-edit.php': 'تعديل بكسل',
    'language.php': 'اللغة',
    'color-add.php': 'إضافة لون',
    'color-edit.php': 'تعديل لون',
    'exchange-requests.php': 'طلبات الاستبدال',
    'country-add.php': 'إضافة ولاية',
    'country-edit.php': 'تعديل ولاية',
    'shipping-cost-edit.php': 'تعديل تكلفة الشحن',
    'customer-add.php': 'إضافة عميل',
    'customer-edit.php': 'تعديل عميل',
    'employees.php': 'الموظفون',
    'employee-ranking.php': 'ترتيب الموظفين',
    'employee-details.php': 'تفاصيل الموظف',
    'employee-add.php': 'إضافة موظف',
    'event-settings.php': 'إعدادات الأحداث',
    'ai-insights.php': 'تحليلات الذكاء الاصطناعي',
    'complaints.php': 'الشكاوى والملاحظات',
    'telegram-dashboard.php': 'لوحة تحكم بوت Telegram',
    'telegram-settings.php': 'إعدادات بوت Telegram',
  },
  fr: {
    'index.php': 'Tableau de bord',
    'store.php': 'Boutique',
    'store-dashboard.php': 'Boutique Dashboard',
    'settings.php': 'Paramètres',
    'profile-edit.php': 'Profil',
    'site-security.php': 'Sécurité',
    'system-health.php': 'État du système',
    'integrations.php': 'Intégrations',
    'performance-settings.php': 'Paramètres de performance',
    'users.php': 'Utilisateurs',
    'product.php': 'Produits',
    'product-add.php': 'Ajouter produit',
    'product-edit.php': 'Modifier produit',
    'size.php': 'Tailles',
    'size-add.php': 'Ajouter taille',
    'size-edit.php': 'Modifier taille',
    'color.php': 'Couleurs',
    'country.php': 'Pays & États',
    'shipping-cost.php': 'Frais de livraison',
    'delivery_list.php': 'Liste de livraison',
    'delivery-company.php': 'Sociétés de livraison',
    'order.php': 'Commandes',
    'order-statistics.php': 'Statistiques',
    'order-details.php': 'Détails commande',
    'incomplete-orders.php': 'Commandes incomplètes',
    'ecotrack-diagnostics.php': 'Diagnostics Ecotrack',
    'customer.php': 'Clients',
    'customer-message.php': 'Messages clients',
    'slider.php': 'Slider',
    'slider-add.php': 'Ajouter slider',
    'slider-edit.php': 'Modifier slider',
    'service.php': 'Services',
    'service-add.php': 'Ajouter service',
    'service-edit.php': 'Modifier service',
    'faq.php': 'FAQ',
    'page.php': 'Pages',
    'photo.php': 'Galerie',
    'photo-add.php': 'Ajouter photo',
    'photo-edit.php': 'Modifier photo',
    'social-media.php': 'Réseaux sociaux',
    'top-category.php': 'Catégories principales',
    'mid-category.php': 'Sous-catégories',
    'end-category.php': 'Catégories finales',
    'billing.php': 'Facturation',
    'commission-settings.php': 'Commissions',
    'disaster-recovery.php': 'Récupération d\'urgence',
    'queue-dashboard.php': 'Files d\'attente',
    'audit-log.php': 'Journal d\'audit',
    'api-keys.php': 'Clés API',
    'backups.php': 'Sauvegardes',
    'pixel.php': 'Pixels de suivi',
    'pixel-add.php': 'Ajouter pixel',
    'pixel-edit.php': 'Modifier pixel',
    'language.php': 'Langues',
    'color-add.php': 'Ajouter couleur',
    'color-edit.php': 'Modifier couleur',
    'exchange-requests.php': 'Demandes d\'échange',
    'country-add.php': 'Ajouter état',
    'country-edit.php': 'Modifier état',
    'shipping-cost-edit.php': 'Modifier frais de livraison',
    'customer-add.php': 'Ajouter client',
    'customer-edit.php': 'Modifier client',
    'employees.php': 'Employés',
    'employee-ranking.php': 'Classement des employés',
    'employee-details.php': 'Détails de l\'employé',
    'employee-add.php': 'Ajouter employé',
    'event-settings.php': 'Paramètres d\'événements',
    'ai-insights.php': 'Analyses IA',
    'complaints.php': 'Plaintes & Remarques',
    'telegram-dashboard.php': 'Dashboard du Bot Telegram',
    'telegram-settings.php': 'Paramètres du Bot Telegram',
  },
  en: {
    'index.php': 'Dashboard',
    'store.php': 'Store',
    'store-dashboard.php': 'Store Dashboard',
    'settings.php': 'Settings',
    'profile-edit.php': 'Profile',
    'site-security.php': 'Security',
    'system-health.php': 'System Health',
    'integrations.php': 'Integrations',
    'performance-settings.php': 'Performance Settings',
    'users.php': 'Users',
    'product.php': 'Products',
    'product-add.php': 'Add Product',
    'product-edit.php': 'Edit Product',
    'size.php': 'Sizes',
    'size-add.php': 'Add Size',
    'size-edit.php': 'Edit Size',
    'color.php': 'Colors',
    'country.php': 'Countries & States',
    'shipping-cost.php': 'Shipping Costs',
    'delivery_list.php': 'Delivery List',
    'delivery-company.php': 'Delivery Companies',
    'order.php': 'Orders',
    'order-statistics.php': 'Order Statistics',
    'order-details.php': 'Order Details',
    'incomplete-orders.php': 'Incomplete Orders',
    'ecotrack-diagnostics.php': 'Ecotrack Diagnostics',
    'customer.php': 'Customers',
    'customer-message.php': 'Customer Messages',
    'slider.php': 'Slider',
    'slider-add.php': 'Add Slider',
    'slider-edit.php': 'Edit Slider',
    'service.php': 'Services',
    'service-add.php': 'Add Service',
    'service-edit.php': 'Edit Service',
    'faq.php': 'FAQ',
    'page.php': 'Pages',
    'photo.php': 'Gallery',
    'photo-add.php': 'Add Photo',
    'photo-edit.php': 'Edit Photo',
    'social-media.php': 'Social Media',
    'top-category.php': 'Top Categories',
    'mid-category.php': 'Mid Categories',
    'end-category.php': 'End Categories',
    'billing.php': 'Billing',
    'commission-settings.php': 'Commissions',
    'disaster-recovery.php': 'Disaster Recovery',
    'queue-dashboard.php': 'Queues',
    'audit-log.php': 'Audit Log',
    'api-keys.php': 'API Keys',
    'backups.php': 'Backups',
    'pixel.php': 'Pixels',
    'pixel-add.php': 'Add Pixel',
    'pixel-edit.php': 'Edit Pixel',
    'language.php': 'Language',
    'color-add.php': 'Add Color',
    'color-edit.php': 'Edit Color',
    'exchange-requests.php': 'Exchange Requests',
    'country-add.php': 'Add State',
    'country-edit.php': 'Edit State',
    'shipping-cost-edit.php': 'Edit Shipping Cost',
    'customer-add.php': 'Add Customer',
    'customer-edit.php': 'Edit Customer',
    'employees.php': 'Employees',
    'employee-ranking.php': 'Employee Ranking',
    'employee-details.php': 'Employee Details',
    'employee-add.php': 'Add Employee',
    'event-settings.php': 'Event Settings',
    'ai-insights.php': 'AI Insights',
    'complaints.php': 'Complaints & Notes',
    'telegram-dashboard.php': 'Telegram Bot Dashboard',
    'telegram-settings.php': 'Telegram Bot Settings',
  }
}

export const headerSections = {
  // Arabic keys
  'المنتجات': 'catalog',
  'الطلبات': 'sales',
  'المتجر': 'catalog',
  'الفريق والموظفون': 'people',
  'الأحداث والتتبع': 'automation',
  'النظام': 'system',
  // French keys
  'Produits': 'catalog',
  'Commandes': 'sales',
  'Boutique': 'catalog',
  'Équipe & Personnel': 'people',
  'Événements & Suivi': 'automation',
  'Système': 'system',
  // English keys
  'Products': 'catalog',
  'Orders': 'sales',
  'Store': 'catalog',
  'Team & Staff': 'people',
  'Events & Tracking': 'automation',
  'System': 'system',
}

export const headerTranslations = {
  ar: {
    // Arabic originals
    'المنتجات': 'المنتجات',
    'الطلبات': 'الطلبات',
    'المتجر': 'المتجر',
    'الفريق والموظفون': 'الفريق والموظفون',
    'الأحداث والتتبع': 'الأحداث والتتبع',
    'النظام': 'النظام',
    // French → Arabic
    'Produits': 'المنتجات',
    'Commandes': 'الطلبات',
    'Boutique': 'المتجر',
    'Équipe & Personnel': 'الفريق والموظفون',
    'Événements & Suivi': 'الأحداث والتتبع',
    'Système': 'النظام',
    // English → Arabic
    'Products': 'المنتجات',
    'Orders': 'الطلبات',
    'Store': 'المتجر',
    'Team & Staff': 'الفريق والموظفون',
    'Events & Tracking': 'الأحداث والتتبع',
    'System': 'النظام',
  },
  fr: {
    // Arabic → French
    'المنتجات': 'Produits',
    'الطلبات': 'Commandes',
    'المتجر': 'Boutique',
    'الفريق والموظفون': 'Équipe & Personnel',
    'الأحداث والتتبع': 'Événements & Suivi',
    'النظام': 'Système',
    // French originals (pass-through)
    'Produits': 'Produits',
    'Commandes': 'Commandes',
    'Boutique': 'Boutique',
    'Équipe & Personnel': 'Équipe & Personnel',
    'Événements & Suivi': 'Événements & Suivi',
    'Système': 'Système',
    // English → French
    'Products': 'Produits',
    'Orders': 'Commandes',
    'Store': 'Boutique',
    'Team & Staff': 'Équipe & Personnel',
    'Events & Tracking': 'Événements & Suivi',
    'System': 'Système',
  },
  en: {
    // Arabic → English
    'المنتجات': 'Products',
    'الطلبات': 'Orders',
    'المتجر': 'Store',
    'الفريق والموظفون': 'Team & Staff',
    'الأحداث والتتبع': 'Events & Tracking',
    'النظام': 'System',
    // French → English
    'Produits': 'Products',
    'Commandes': 'Orders',
    'Boutique': 'Store',
    'Équipe & Personnel': 'Team & Staff',
    'Événements & Suivi': 'Events & Tracking',
    'Système': 'System',
    // English originals (pass-through)
    'Products': 'Products',
    'Orders': 'Orders',
    'Store': 'Store',
    'Team & Staff': 'Team & Staff',
    'Events & Tracking': 'Events & Tracking',
    'System': 'System',
  }
}

export const sectionLabels = new Proxy({}, {
  get(target, prop) {
    const lang = getLanguage()
    return sectionTranslations[lang]?.[prop] || sectionTranslations['ar'][prop] || undefined
  }
})

export const pageNames = new Proxy({}, {
  get(target, prop) {
    const lang = getLanguage()
    return pageNameTranslations[lang]?.[prop] || pageNameTranslations['ar'][prop] || undefined
  }
})

export const sectionIcons = {
  overview: IconLayoutDashboard,
  sales: IconShoppingCart,
  catalog: IconShoppingBag,
  people: IconUsersGroup,
  content: IconFileText,
  finance: IconCreditCard,
  automation: IconRobot,
  system: IconSettings,
}

export function getSectionForFile(file, title = '') {
  const cleanTitle = (title || '').trim()
  if (headerSections[cleanTitle]) {
    return headerSections[cleanTitle]
  }
  if (!file || file === 'index.php' || file === 'store.php' || file === 'store-dashboard.php') return 'overview'
  if (/^(order|incomplete|ecotrack|exchange)/.test(file)) return 'sales'
  if (/^(product|size|color|country|shipping|delivery|top-category|mid-category|end-category)/.test(file)) return 'catalog'
  if (/^(customer|users|employee|commission)/.test(file)) return 'people'
  if (/^(slider|service|faq|page|photo|social|language)/.test(file)) return 'content'
  if (/^(billing|payment|invoice)/.test(file)) return 'finance'
  if (/^(queue|ai|recovery|telegram|pixel|automation)/.test(file)) return 'automation'
  return 'system'
}

export function getPageTitle(file, fallback = '') {
  const lang = getLanguage()
  const cleanFallback = (fallback || '').trim()
  if (headerTranslations[lang]?.[cleanFallback]) {
    return headerTranslations[lang][cleanFallback]
  }
  return pageNames[file] || fallback || 'لوحة التحكم'
}

export function getIconForFile(file, section) {
  if (/^order/.test(file)) return IconClipboardList
  if (/^incomplete/.test(file)) return IconBell
  if (/^ecotrack|^delivery/.test(file)) return IconTruck
  if (/^product/.test(file)) return IconPackage
  if (/category/.test(file)) return IconCategory
  if (/^size|^color|^settings|^performance/.test(file)) return IconAdjustments
  if (/^customer/.test(file)) return IconUsers
  if (/^users|employee/.test(file)) return IconUsersGroup
  if (/^slider/.test(file)) return IconSlideshow
  if (/^photo/.test(file)) return IconPhoto
  if (/^service|^page|^faq/.test(file)) return IconFileText
  if (/^store/.test(file)) return IconBuildingStore
  if (/^billing|payment|commission/.test(file)) return IconCashBanknote
  if (/^disaster|backup/.test(file)) return IconShieldCheck
  if (/^queue/.test(file)) return IconArchive
  if (/^audit|system-health/.test(file)) return IconFileAnalytics
  if (/^api/.test(file)) return IconKey
  if (/^integrations/.test(file)) return IconWorld
  if (/^pixel/.test(file)) return IconChartBar
  if (/^telegram|message/.test(file)) return IconMessage
  if (/health/.test(file)) return IconHeartbeat
  if (/database|sql/.test(file)) return IconDatabase
  if (/help|support/.test(file)) return IconLifebuoy
  if (/^index/.test(file)) return IconLayoutDashboard
  return sectionIcons[section] || IconBox
}

export const pageTranslations = {
  ar: {
    // Dashboard
    totalOrders: 'إجمالي الطلبات',
    revenue: 'الإيراد',
    products: 'المنتجات',
    customers: 'العملاء',
    storeCenter: 'مركز المتجر',
    execSummary: 'ملخص تنفيذي',
    openOrders: 'فتح الطلبات',
    salesRevenue: 'إيرادات المبيعات',
    compareSalesOrders: 'مقارنة المبيعات والطلبات',
    orders: 'الطلبات',
    noData: 'لا توجد بيانات',
    revenueTitle: 'الإيرادات',
    salesOrdersTitle: 'المبيعات والطلبات',

    // SettingsPage
    storeSettings: 'إعدادات المتجر',
    settingsDesc: 'واجهة مختصرة لإدارة الهوية، بيانات التواصل، التكاملات، التتبع، والسكربتات مع الحفاظ على نماذج PHP الأصلية.',
    sections: 'الأقسام',
    forms: 'النماذج',
    fields: 'الحقول',
    files: 'الملفات',
    sectionsDesc: 'الأقسام المعروضة فقط',
    formsDesc: 'مسارات الحفظ كما هي',
    fieldsDesc: 'حقول قابلة للتحرير',
    filesDesc: 'رفع صور وملفات',
    settingsSections: 'أقسام الإعدادات',
    saveSection: 'حفظ القسم',
    formCount: 'نموذج',
    fieldCount: 'حقل',

    // ContentPage
    modules: 'الوحدات',
    modulesDesc: 'بطاقات ومؤشرات تشغيلية',
    healthy: 'سليم',
    healthyDesc: 'مؤشرات دون إنذار',
    warnings: 'تنبيهات',
    warningsDesc: 'تحتاج متابعة',
    actions: 'إجراءات',
    actionsDesc: 'أوامر متاحة',
    contentPageDesc: 'واجهة تشغيلية موحدة تعرض محتوى الصفحة الأصلي داخل إطار SaaS حديث مع الحفاظ على المسارات والإجراءات كما هي.',
    operationalView: 'Operational view',

    // ProductForm
    basics: 'الأساسيات',
    basicsDesc: 'اسم المنتج والتصنيف',
    pricing: 'التسعير والمخزون',
    pricingDesc: 'الأسعار والكميات',
    contentTab: 'المحتوى',
    contentTabDesc: 'الوصف والملاحظات',
    media: 'الصور والملفات',
    mediaDesc: 'الصور الرئيسية والمعرض',
    options: 'النشر والتتبع',
    optionsDesc: 'الحالة والخيارات',
    formDesc: 'نموذج حديث متزامن مع النموذج الأصلي لضمان بقاء الحفظ، التحقق، والرفع كما هي في الخلفية.',
    completeness: 'الاكتمال',
    saveChanges: 'حفظ التعديلات',
    save: 'حفظ',
    previous: 'السابق',
    next: 'التالي',
    confirmSave: 'تأكيد وحفظ',
    formSummary: 'ملخص النموذج',
    syncDesc: 'يتزامن مع نموذج PHP الأصلي',
    compRatio: 'نسبة الاكتمال',
    ready: 'جاهز',
    needsReview: 'يحتاج مراجعة',
    required: 'مطلوب',
    chooseFile: 'اختيار ملف',
    noFileChosen: 'لم يتم اختيار ملف',

    // Quick Actions
    quickActionsOrders: 'الطلبات',
    quickActionsNewProduct: 'منتج جديد',
    quickActionsRecoverOrders: 'استرجاع الطلبات',
    quickActionsSystemHealth: 'صحة النظام',
    editData: 'تعديل البيانات',
    addData: 'إضافة البيانات',
    editProductDetails: 'تعديل بيانات المنتج',
    addNewProduct: 'إضافة منتج جديد',
    comma: '،',

    // Orders / Tables
    dateCol: 'التاريخ',
    dataEyebrow: 'البيانات',
    tablesCount: 'الجداول',
    recordsCount: 'السجلات',
    afterFilter: 'بعد الفلترة',
    searchPlaceholderTable: 'بحث سريع في كل الأعمدة...',
    densityComfortable: 'كثافة مريحة',
    resetFilter: 'إعادة ضبط',
    selectedCount: 'سجل محدد',
    noBulkActions: 'لا توجد إجراءات جماعية',
    noRecords: 'لا توجد سجلات',
    noFilteredResults: 'لا توجد نتائج مطابقة للبحث الحالي.',
    paginationText: 'من',
    salesEyebrow: 'المبيعات',
    ordersManagement: 'إدارة الطلبات',
    ordersDesc: 'مركز عمل موحد للمبيعات والمتابعة.',
    statistics: 'الإحصائيات',
    incomplete: 'غير مكتملة',
    searchOrdersPlaceholder: 'بحث بالرقم، العميل، الهاتف، المنتج، الموظف...',
    allEmployees: 'جميع الموظفين',
    unassigned: 'غير موزع',
    allDeliveries: 'كل طرق التوصيل',
    filter: 'تصفية',
    selectedOrdersCount: 'طلب محدد',
    orderCol: 'الطلب',
    productCol: 'المنتج',
    customerCol: 'العميل',
    employeeCol: 'الموظف',
    followupCol: 'المتابعة',
    deliveryCol: 'التوصيل',
    statusCol: 'الحالة',
    priceCol: 'القيمة',
    quantityLabel: 'الكمية',
    notSet: 'غير محدد',
    actionPrimary: 'الإجراء الأساسي',
    actionDetails: 'تفاصيل',
    actionDelete: 'حذف',
    noOrders: 'لا توجد طلبات',
    noOrdersDesc: 'غير الفلاتر أو افتح تبويباً آخر لعرض الطلبات.',
    orderDetailTitle: 'تفاصيل الطلب',
    confirmDeleteTitle: 'تأكيد الحذف',
    confirmDeleteDesc: 'سيتم حذف الطلب {id}. هذا الإجراء يعتمد على مسار الحذف الحالي ولا يمكن التراجع عنه من هنا.',
    cancel: 'إلغاء',
    deleteOrder: 'حذف الطلب',
    summaryTotal: 'إجمالي الطلبات',
    summaryTotalDesc: 'كل الحالات الحالية',
    summaryToday: 'طلبات اليوم',
    summaryTodayDesc: 'مسجلة بتاريخ اليوم',
    summaryPending: 'بانتظار التأكيد',
    summaryPendingDesc: 'بلا اتصال',
    summaryCompleted: 'القيمة المؤكدة',
    summaryCompletedDesc: 'جاهزة للتأكيد',
    descProduct: 'إدارة المنتجات، المخزون، الأسعار، وحالة النشر من جدول موحد وسريع.',
    descCustomer: 'عرض العملاء والرسائل والحسابات مع بحث سريع وإجراءات مباشرة.',
    descDelivery: 'إدارة التوصيل، الشركات، والأسعار حسب المناطق.',
    descSystem: 'مراقبة تشغيلية مهيكلة للأنظمة، السجلات، والطوابير.',
    descBilling: 'إدارة الفوترة، الاشتراكات، والعمولات.',
    descDefault: 'جدول إداري حديث مع بحث، فرز، تحديد جماعي، وإجراءات سريعة.',
    performanceCurve: 'منحنى الأداء',
    latestOrdersValue: 'قيمة أحدث الطلبات',
    analytics: 'التحليلات',
    quickActionsTitle: 'إجراءات سريعة',
    workflow: 'سير العمل',
    latestActiveOrders: 'آخر الطلبات النشطة',
    viewAll: 'عرض الكل',
    inventoryAlerts: 'تنبيهات المخزون',
    manage: 'إدارة',
    noInventoryAlerts: 'لا توجد تنبيهات مخزون حالياً.',
  },
  fr: {
    // Dashboard
    totalOrders: 'Total Commandes',
    revenue: 'Chiffre d’affaires',
    products: 'Produits',
    customers: 'Clients',
    storeCenter: 'Centre boutique',
    execSummary: 'Résumé exécutif',
    openOrders: 'Ouvrir commandes',
    salesRevenue: 'Chiffre d’affaires',
    compareSalesOrders: 'Comparaison Ventes & Commandes',
    orders: 'Commandes',
    noData: 'Aucune donnée',
    revenueTitle: 'Chiffre d’affaires',
    salesOrdersTitle: 'Ventes & Commandes',

    // SettingsPage
    storeSettings: 'Paramètres boutique',
    settingsDesc: 'Interface concise pour gérer l’identité, les contacts, les intégrations, le suivi et les scripts tout en conservant les formulaires PHP originaux.',
    sections: 'Sections',
    forms: 'Formulaires',
    fields: 'Champs',
    files: 'Fichiers',
    sectionsDesc: 'Sections affichées uniquement',
    formsDesc: 'Sauvegarde des chemins en l’état',
    fieldsDesc: 'Champs modifiables',
    filesDesc: 'Téléchargement images & fichiers',
    settingsSections: 'Sections de configuration',
    saveSection: 'Enregistrer la section',
    formCount: 'formulaire',
    fieldCount: 'champ',

    // ContentPage
    modules: 'Modules',
    modulesDesc: 'Cartes et indicateurs opérationnels',
    healthy: 'Sain',
    healthyDesc: 'Indicateurs sans alerte',
    warnings: 'Alertes',
    warningsDesc: 'Nécessite un suivi',
    actions: 'Actions',
    actionsDesc: 'Commandes disponibles',
    contentPageDesc: 'Une interface opérationnelle unifiée affichant le contenu original de la page dans un framework SaaS moderne tout en préservant les chemins et les actions.',
    operationalView: 'Vue opérationnelle',

    // ProductForm
    basics: 'Bases',
    basicsDesc: 'Nom du produit & catégorie',
    pricing: 'Prix & Stock',
    pricingDesc: 'Tarifs et quantités',
    contentTab: 'Contenu',
    contentTabDesc: 'Description & notes',
    media: 'Médias & Fichiers',
    mediaDesc: 'Images principales & galerie',
    options: 'Publication & Suivi',
    optionsDesc: 'Statut et options',
    formDesc: 'Formulaire moderne synchronisé pour garantir la persistance des sauvegardes, validations et transferts.',
    completeness: 'Complétude',
    saveChanges: 'Enregistrer modifications',
    save: 'Enregistrer',
    previous: 'Précédent',
    next: 'Suivant',
    confirmSave: 'Confirmer & Enregistrer',
    formSummary: 'Résumé du formulaire',
    syncDesc: 'Synchronisé avec le formulaire PHP d\'origine',
    compRatio: 'Taux de complétude',
    ready: 'Prêt',
    needsReview: 'À réviser',
    required: 'Requis',
    chooseFile: 'Choisir fichier',
    noFileChosen: 'Aucun fichier choisi',

    // Quick Actions
    quickActionsOrders: 'Commandes',
    quickActionsNewProduct: 'Nouveau produit',
    quickActionsRecoverOrders: 'Récupérer commandes',
    quickActionsSystemHealth: 'État du système',
    editData: 'Modifier les données',
    addData: 'Ajouter des données',
    editProductDetails: 'Modifier les détails du produit',
    addNewProduct: 'Ajouter un nouveau produit',
    comma: ',',

    // Orders / Tables
    dateCol: 'Date',
    dataEyebrow: 'Données',
    tablesCount: 'Tables',
    recordsCount: 'Registres',
    afterFilter: 'Filtré',
    searchPlaceholderTable: 'Recherche rapide dans toutes les colonnes...',
    densityComfortable: 'Densité confortable',
    resetFilter: 'Réinitialiser',
    selectedCount: 'enregistrements sélectionnés',
    noBulkActions: 'Aucune action groupée',
    noRecords: 'Aucun enregistrement',
    noFilteredResults: 'Aucun résultat ne correspond à votre recherche.',
    paginationText: 'sur',
    salesEyebrow: 'Ventes',
    ordersManagement: 'Gestion des commandes',
    ordersDesc: 'Centre de travail unifié pour le suivi et les ventes.',
    statistics: 'Statistiques',
    incomplete: 'Incomplètes',
    searchOrdersPlaceholder: 'Rechercher par ID, client, téléphone, produit, employé...',
    allEmployees: 'Tous les employés',
    unassigned: 'Non attribué',
    allDeliveries: 'Toutes les livraisons',
    filter: 'Filtrer',
    selectedOrdersCount: 'commandes sélectionnées',
    orderCol: 'Commande',
    productCol: 'Produit',
    customerCol: 'Client',
    employeeCol: 'Employé',
    followupCol: 'Suivi',
    deliveryCol: 'Livraison',
    statusCol: 'Statut',
    priceCol: 'Valeur',
    quantityLabel: 'Quantité',
    notSet: 'Non défini',
    actionPrimary: 'Action principale',
    actionDetails: 'Détails',
    actionDelete: 'Supprimer',
    noOrders: 'Aucune commande',
    noOrdersDesc: 'Changez les filtres ou ouvrez un autre onglet pour afficher les commandes.',
    orderDetailTitle: 'Détails de la commande',
    confirmDeleteTitle: 'Confirmer la suppression',
    confirmDeleteDesc: 'La commande {id} sera supprimée. Cette action ne peut pas être annulée.',
    cancel: 'Annuler',
    deleteOrder: 'Supprimer la commande',
    summaryTotal: 'Total Commandes',
    summaryTotalDesc: 'Tous les états actuels',
    summaryToday: 'Commandes du jour',
    summaryTodayDesc: 'Enregistrées aujourd\'hui',
    summaryPending: 'En attente de confirmation',
    summaryPendingDesc: 'sans appel',
    summaryCompleted: 'Valeur confirmée',
    summaryCompletedDesc: 'prêtes pour confirmation',
    descProduct: 'Gérez les produits, le stock, les prix et le statut de publication.',
    descCustomer: 'Affichez les clients, les messages et les comptes.',
    descDelivery: 'Gérez la livraison, les transporteurs et les frais.',
    descSystem: 'Surveillance opérationnelle des systèmes et des files d\'attente.',
    descBilling: 'Gérez la facturation, les abonnements et les commissions.',
    descDefault: 'Tableau d\'administration moderne avec recherche et tri.',
    performanceCurve: 'Courbe de performance',
    latestOrdersValue: 'Valeur des dernières commandes',
    analytics: 'Analyses',
    quickActionsTitle: 'Actions rapides',
    workflow: 'Flux de travail',
    latestActiveOrders: 'Dernières commandes actives',
    viewAll: 'Voir tout',
    inventoryAlerts: 'Alertes de stock',
    manage: 'Gérer',
    noInventoryAlerts: 'Aucune alerte de stock pour le moment.',
  },
  en: {
    // Dashboard
    totalOrders: 'Total Orders',
    revenue: 'Revenue',
    products: 'Products',
    customers: 'Customers',
    storeCenter: 'Store Center',
    execSummary: 'Executive Summary',
    openOrders: 'Open Orders',
    salesRevenue: 'Sales Revenue',
    compareSalesOrders: 'Sales & Orders Comparison',
    orders: 'Orders',
    noData: 'No data',
    revenueTitle: 'Revenue',
    salesOrdersTitle: 'Sales & Orders',

    // SettingsPage
    storeSettings: 'Store Settings',
    settingsDesc: 'A concise interface to manage identity, contact details, integrations, tracking, and scripts while preserving the original PHP forms.',
    sections: 'Sections',
    forms: 'Forms',
    fields: 'Fields',
    files: 'Files',
    sectionsDesc: 'Displayed sections only',
    formsDesc: 'Save paths as they are',
    fieldsDesc: 'Editable fields',
    filesDesc: 'Upload images & files',
    settingsSections: 'Settings Sections',
    saveSection: 'Save Section',
    formCount: 'form',
    fieldCount: 'field',

    // ContentPage
    modules: 'Modules',
    modulesDesc: 'Operational cards & indicators',
    healthy: 'Healthy',
    healthyDesc: 'Indicators without alert',
    warnings: 'Warnings',
    warningsDesc: 'Requires follow-up',
    actions: 'Actions',
    actionsDesc: 'Available commands',
    contentPageDesc: 'A unified operational interface displaying the original page content within a modern SaaS framework while preserving paths and actions.',
    operationalView: 'Operational view',

    // ProductForm
    basics: 'Basics',
    basicsDesc: 'Product name & category',
    pricing: 'Pricing & Stock',
    pricingDesc: 'Prices and quantities',
    contentTab: 'Content',
    contentTabDesc: 'Description & notes',
    media: 'Media & Files',
    mediaDesc: 'Main images & gallery',
    options: 'Publishing & Tracking',
    optionsDesc: 'Status and options',
    formDesc: 'Modern form synchronized with the original form to ensure save, validation, and upload persist in the background.',
    completeness: 'Completeness',
    saveChanges: 'Save Changes',
    save: 'Save',
    previous: 'Previous',
    next: 'Next',
    confirmSave: 'Confirm & Save',
    formSummary: 'Form Summary',
    syncDesc: 'Synchronized with the original PHP form',
    compRatio: 'Completeness ratio',
    ready: 'Ready',
    needsReview: 'Needs review',
    required: 'Required',
    chooseFile: 'Choose file',
    noFileChosen: 'No file chosen',

    // Quick Actions
    quickActionsOrders: 'Orders',
    quickActionsNewProduct: 'New Product',
    quickActionsRecoverOrders: 'Recover Orders',
    quickActionsSystemHealth: 'System Health',
    editData: 'Edit Data',
    addData: 'Add Data',
    editProductDetails: 'Edit Product Details',
    addNewProduct: 'Add New Product',
    comma: ',',

    // Orders / Tables
    dateCol: 'Date',
    dataEyebrow: 'Data',
    tablesCount: 'Tables',
    recordsCount: 'Records',
    afterFilter: 'Filtered',
    searchPlaceholderTable: 'Quick search in all columns...',
    densityComfortable: 'Comfortable density',
    resetFilter: 'Reset',
    selectedCount: 'records selected',
    noBulkActions: 'No bulk actions',
    noRecords: 'No records found',
    noFilteredResults: 'No results match your search query.',
    paginationText: 'of',
    salesEyebrow: 'Sales',
    ordersManagement: 'Orders Management',
    ordersDesc: 'Unified workspace for sales and followups.',
    statistics: 'Statistics',
    incomplete: 'Incomplete',
    searchOrdersPlaceholder: 'Search by ID, customer, phone, product, employee...',
    allEmployees: 'All Employees',
    unassigned: 'Unassigned',
    allDeliveries: 'All Deliveries',
    filter: 'Filter',
    selectedOrdersCount: 'orders selected',
    orderCol: 'Order',
    productCol: 'Product',
    customerCol: 'Customer',
    employeeCol: 'Employee',
    followupCol: 'Follow-up',
    deliveryCol: 'Delivery',
    statusCol: 'Status',
    priceCol: 'Value',
    quantityLabel: 'Qty',
    notSet: 'Not set',
    actionPrimary: 'Primary action',
    actionDetails: 'Details',
    actionDelete: 'Delete',
    noOrders: 'No orders',
    noOrdersDesc: 'Modify filters or select another tab to view orders.',
    orderDetailTitle: 'Order Details',
    confirmDeleteTitle: 'Confirm Delete',
    confirmDeleteDesc: 'Order {id} will be deleted. This action cannot be undone.',
    cancel: 'Cancel',
    deleteOrder: 'Delete Order',
    summaryTotal: 'Total Orders',
    summaryTotalDesc: 'All current statuses',
    summaryToday: 'Today\'s Orders',
    summaryTodayDesc: 'Registered today',
    summaryPending: 'Pending Confirmation',
    summaryPendingDesc: 'without call',
    summaryCompleted: 'Confirmed Value',
    summaryCompletedDesc: 'ready for confirmation',
    descProduct: 'Manage products, stock, pricing, and publishing status.',
    descCustomer: 'View customers, messages, and accounts with quick search.',
    descDelivery: 'Manage delivery, companies, and rates.',
    descSystem: 'Structured operational monitoring of systems and queues.',
    descBilling: 'Manage billing, subscriptions, and commissions.',
    descDefault: 'Modern admin table with search, sorting and bulk actions.',
    performanceCurve: 'Performance Curve',
    latestOrdersValue: 'Latest Orders Value',
    analytics: 'Analytics',
    quickActionsTitle: 'Quick Actions',
    workflow: 'Workflow',
    latestActiveOrders: 'Latest Active Orders',
    viewAll: 'View All',
    inventoryAlerts: 'Inventory Alerts',
    manage: 'Manage',
    noInventoryAlerts: 'No current inventory alerts.',
  }
}

export const quickActions = new Proxy([], {
  get(target, prop) {
    const lang = getLanguage()
    const trans = pageTranslations[lang] || pageTranslations['ar']
    const actions = [
      { href: 'order.php', label: trans.quickActionsOrders, icon: IconClipboardList },
      { href: 'product-add.php', label: trans.quickActionsNewProduct, icon: IconPackage },
      { href: 'incomplete-orders.php', label: trans.quickActionsRecoverOrders, icon: IconBell },
      { href: 'system-health.php', label: trans.quickActionsSystemHealth, icon: IconHeartbeat },
    ]
    if (typeof actions[prop] === 'function') {
      return actions[prop].bind(actions)
    }
    return actions[prop]
  }
})

export const legacyMappers = {
  totalOrders: /إجمالي الطلبات|total orders/i,
  revenue: /الإيراد|المدخول|revenue|income/i,
  products: /المنتجات|products/i,
  customers: /العملاء|customers/i,
  openOrders: /فتح الطلبات|open orders/i,
  pending: /بانتظار التأكيد|معلق|pending/i,
  today: /نشطة|اليوم|today/i,
  completed: /القيمة المؤكدة|completed/i,
  noData: /لا توجد بيانات|no data/i,
  quickOrders: /الطلبات|طلبات|orders/i,
  quickProduct: /منتج|product/i,
  quickRecover: /استرجاع|recover/i,
  quickHealth: /صحة|health/i,
  kpiRevenue: /إيراد|القيمة|revenue/i,
  kpiCustomers: /عملاء|موظف/i,
  kpiProducts: /منتج|مخزون/i,
  kpiPending: /معلق|انتظار/i,
  kpiCompleted: /مكتمل|مؤكد/i,
  colPhone: /ip|هاتف|phone/i,
  colDateTime: /date|time|تاريخ|وقت/i,
  colDataValue: /data|value|json|message|بيانات|قيمة|رسالة/i,
  kpiLow: /منخفض|low/i,
  colAction: /action|إجراء|حذف|edit|delete/i,
  toneSuccess: /completed|confirmed|paid|active|success|healthy|مكتمل|مؤكد|نشط|سليمة|ناجح|تم/i,
  toneWarning: /pending|warning|review|انتظار|معلق|تحذير|مراجعة|قيد/i,
  toneDanger: /cancel|returned|failed|critical|danger|ملغي|مرتجع|فشل|حرج|خطر|خطأ/i,
}

export const legacyOrdersMappers = {
  unassigned: /غير موزع|unassigned/i,
  order: /طلب|order/i,
}

const sharedTranslations = {
  ar: {
    administration: 'الإدارة',
    add: 'إضافة',
    viewAll: 'عرض الكل',
    back: 'رجوع',
    noData: 'لا توجد بيانات',
    noDataDesc: 'لم يتم العثور على سجلات مطابقة للفلاتر الحالية.',
    brandName: 'متجر الثقة',
    adminFallback: 'المدير',
    controlPanel: 'لوحة التحكم',
  },
  fr: {
    administration: 'Administration',
    add: 'Ajouter',
    viewAll: 'Voir tout',
    back: 'Retour',
    noData: 'Aucune donnée',
    noDataDesc: 'Aucun enregistrement ne correspond aux filtres actuels.',
    brandName: 'Boutique El Thika',
    adminFallback: 'Administrateur',
    controlPanel: 'Tableau de bord',
  },
  en: {
    administration: 'Administration',
    add: 'Add',
    viewAll: 'View All',
    back: 'Back',
    noData: 'No data',
    noDataDesc: 'No records match the current filters.',
    brandName: 'El Thika Store',
    adminFallback: 'Administrator',
    controlPanel: 'Control Panel',
  }
}

export const sharedTrans = new Proxy({}, {
  get(target, prop) {
    const lang = getLanguage()
    return sharedTranslations[lang]?.[prop] || sharedTranslations['ar'][prop] || ''
  }
})

export const langLabels = {
  ar: 'العربية',
  fr: 'Français',
  en: 'English',
}

export const langFlags = {
  ar: '🇩🇿',
  fr: '🇫🇷',
  en: '🇺🇸',
}

export const uiTranslations = {
  ar: {
    quickActions: 'إجراءات سريعة',
    notifications: 'التنبيهات',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    searchPlaceholder: 'ابحث عن صفحة أو إجراء...',
    noResults: 'لا توجد نتائج مطابقة',
    viewStore: 'عرض المتجر',
    closeMenu: 'إغلاق القائمة',
    expandMenu: 'توسيع القائمة',
    collapseMenu: 'تصغير القائمة',
    activeNotifications: 'التنبيهات',
    noActiveNotifications: 'لا توجد تنبيهات نشطة',
    attentionRequired: 'عناصر تحتاج متابعة',
    pendingConfirm: 'طلبات تنتظر التأكيد',
    noCalls: 'طلبات بلا اتصال',
    followups: 'متابعات مطلوبة',
    lowStock: 'منتجات منخفضة المخزون',
    dashboard: 'لوحة التحكم',
    adminConsole: 'لوحة التحكم',
  },
  fr: {
    quickActions: 'Actions rapides',
    notifications: 'Notifications',
    profile: 'Profil',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    searchPlaceholder: 'Rechercher une page ou action...',
    noResults: 'Aucun résultat correspondant',
    viewStore: 'Voir la boutique',
    closeMenu: 'Fermer le menu',
    expandMenu: 'Agrandir le menu',
    collapseMenu: 'Réduire le menu',
    activeNotifications: 'Notifications',
    noActiveNotifications: 'Aucune notification active',
    attentionRequired: 'Attention requise',
    pendingConfirm: 'Commandes en attente',
    noCalls: 'Commandes sans appel',
    followups: 'Suivis requis',
    lowStock: 'Stock faible',
    dashboard: 'Tableau de bord',
    adminConsole: 'Console d\'administration',
  },
  en: {
    quickActions: 'Quick Actions',
    notifications: 'Notifications',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    searchPlaceholder: 'Search for page or action...',
    noResults: 'No matching results',
    viewStore: 'View Store',
    closeMenu: 'Close menu',
    expandMenu: 'Expand menu',
    collapseMenu: 'Collapse menu',
    activeNotifications: 'Notifications',
    noActiveNotifications: 'No active notifications',
    attentionRequired: 'Attention required',
    pendingConfirm: 'Pending confirmation',
    noCalls: 'Orders without call',
    followups: 'Followups required',
    lowStock: 'Low stock products',
    dashboard: 'Dashboard',
    adminConsole: 'Admin Console',
  }
}



