<?php
/**
 * Central PHP translation file for Admin Panel
 * Used by all PHP pages to render translated content based on $_SESSION['admin_lang']
 *
 * Usage:
 *   require_once __DIR__ . '/inc/lang.php';
 *   $l = get_lang_strings($current_lang);  // then use $l['key']
 */

function get_lang_strings(string $lang = 'ar'): array {
    $strings = [
        'ar' => [
            // Navigation / Sidebar
            'nav_home'            => 'الرئيسية',
            'nav_store_dash'      => 'لوحة المتجر',
            'nav_products'        => 'المنتجات',
            'nav_manage_products' => 'إدارة المنتجات',
            'nav_top_cat'         => 'الفئات الرئيسية',
            'nav_mid_cat'         => 'الفئات الفرعية',
            'nav_end_cat'         => 'الفئات النهائية',
            'nav_sizes'           => 'المقاسات',
            'nav_colors'          => 'الألوان',
            'nav_orders'          => 'الطلبات',
            'nav_manage_orders'   => 'إدارة الطلبات',
            'nav_statistics'      => 'الإحصائيات',
            'nav_exchange'        => 'طلبات التبديل',
            'nav_incomplete'      => 'الطلبات المعلقة',
            'nav_store'           => 'المتجر',
            'nav_settings'        => 'الإعدادات',
            'nav_slider'          => 'السلايدر',
            'nav_countries'       => 'الولايات / الدول',
            'nav_shipping'        => 'تكاليف التوصيل',
            'nav_people'          => 'الفريق والموظفون',
            'nav_customers'       => 'العملاء',
            'nav_employees'       => 'الموظفين',
            'nav_emp_ranking'     => 'ترتيب الموظفين',
            'nav_commissions'     => 'العمولات',
            'nav_performance'     => 'إعدادات التقييم',
            'nav_delivery_co'     => 'شركات التوصيل',
            'nav_events'          => 'الأحداث والتتبع',
            'nav_event_settings'  => 'مراقبة الأحداث',
            'nav_pixels'          => 'بكسلات التتبع',
            'nav_system'          => 'النظام',
            'nav_telegram'        => 'بوت تيليجرام',
            'nav_telegram_dashboard'=> 'لوحة التحكم',
            'nav_telegram_settings'=> 'إعدادات البوت',
            'nav_security'        => 'أمان الموقع',
            'nav_audit'           => 'سجل التدقيق',
            'nav_health'          => 'صحة النظام',
            'nav_ai'              => 'PHI Insights',
            'nav_users'           => 'إدارة المستخدمين',
            'nav_profile'         => 'الملف الشخصي',
            'nav_logout'          => 'تسجيل الخروج',
            'nav_control_panel'   => 'لوحة التحكم',

            // Common actions
            'add'       => 'إضافة',
            'edit'      => 'تعديل',
            'delete'    => 'حذف',
            'save'      => 'حفظ',
            'cancel'    => 'إلغاء',
            'search'    => 'بحث',
            'actions'   => 'إجراءات',
            'status'    => 'الحالة',
            'date'      => 'التاريخ',
            'name'      => 'الاسم',
            'phone'     => 'الهاتف',
            'price'     => 'السعر',
            'quantity'  => 'الكمية',
            'total'     => 'المجموع',
            'details'   => 'التفاصيل',
            'yes'       => 'نعم',
            'no'        => 'لا',
            'loading'   => 'جاري التحميل...',
            'no_data'   => 'لا توجد بيانات',
            'all'       => 'الكل',
            'filter'    => 'تصفية',
            'back'      => 'رجوع',
            'view_all'  => 'عرض الكل',
            'export'    => 'تصدير',
            'print'     => 'طباعة',

            // Page titles
            'page_dashboard'      => 'لوحة الإدارة',
            'page_products'       => 'إدارة المنتجات',
            'page_orders'         => 'إدارة الطلبات',
            'page_customers'      => 'إدارة العملاء',
            'page_employees'      => 'إدارة الموظفين',
            'page_settings'       => 'إعدادات المتجر',
            'page_delivery'       => 'شركات التوصيل',
            'page_billing'        => 'الفوترة',
            'page_slider'         => 'إدارة السلايدر',
            'page_categories'     => 'الفئات',
            'page_colors'         => 'الألوان',
            'page_sizes'          => 'المقاسات',
            'page_shipping'       => 'تكاليف التوصيل',
            'page_security'       => 'أمان الموقع',
            'page_audit'          => 'سجل التدقيق',
            'page_health'         => 'صحة النظام',
            'page_users'          => 'إدارة المستخدمين',
            'page_statistics'     => 'الإحصائيات',
            'page_commission'     => 'إعدادات العمولات',
            'page_incomplete'     => 'الطلبات المعلقة',
            'page_exchange'       => 'طلبات التبديل',
            'page_pixel'          => 'بكسلات التتبع',
            'page_events'         => 'الأحداث والتتبع',

            // Orders
            'order_id'            => 'رقم الطلب',
            'order_status'        => 'حالة الطلب',
            'order_date'          => 'تاريخ الطلب',
            'order_customer'      => 'العميل',
            'order_employee'      => 'الموظف',
            'order_delivery'      => 'التوصيل',
            'order_product'       => 'المنتج',
            'order_value'         => 'القيمة',
            'order_pending'       => 'معلق',
            'order_confirmed'     => 'مؤكد',
            'order_shipped'       => 'تم الشحن',
            'order_delivered'     => 'مُسلّم',
            'order_cancelled'     => 'ملغي',
            'order_returned'      => 'مُرتجع',
            'add_order'           => 'إضافة طلب',
            'total_orders'        => 'إجمالي الطلبات',
            'pending_orders'      => 'الطلبات المعلقة',
            'today_orders'        => 'طلبات اليوم',

            // Products
            'product_name'        => 'اسم المنتج',
            'product_category'    => 'الفئة',
            'product_price'       => 'السعر',
            'product_stock'       => 'المخزون',
            'product_status'      => 'الحالة',
            'product_published'   => 'منشور',
            'product_hidden'      => 'مخفي',
            'add_product'         => 'إضافة منتج',
            'edit_product'        => 'تعديل المنتج',
            'low_stock'           => 'مخزون منخفض',

            // Customers
            'customer_name'       => 'اسم العميل',
            'customer_phone'      => 'الهاتف',
            'customer_wilaya'     => 'الولاية',
            'customer_orders'     => 'عدد الطلبات',
            'customer_total'      => 'إجمالي المشتريات',
            'add_customer'        => 'إضافة عميل',

            // Employees  
            'employee_name'       => 'اسم الموظف',
            'employee_role'       => 'الدور',
            'employee_orders'     => 'الطلبات المنجزة',
            'employee_commission' => 'العمولة',
            'employee_rank'       => 'الترتيب',

            // Settings
            'store_name'          => 'اسم المتجر',
            'store_logo'          => 'شعار المتجر',
            'store_contact'       => 'معلومات التواصل',
            'store_social'        => 'وسائل التواصل',
            'save_settings'       => 'حفظ الإعدادات',
            'settings_saved'      => 'تم حفظ الإعدادات بنجاح',

            // Common UI
            'num'                    => '#',
            'actions'                => 'الإجراءات',
            'delete'                 => 'حذف',
            'edit'                   => 'تعديل',
            'save'                   => 'حفظ',
            'cancel'                 => 'إلغاء',
            'add_btn'                => 'إضافة',
            'view'                   => 'عرض',
            'search_placeholder'     => 'بحث...',
            'account_status'         => 'حالة الحساب',
            'full_address'           => 'العنوان الكامل',
            'change_status'          => 'تغيير الحالة',
            'confirm_delete_customer'=> 'هل أنت متأكد من حذف هذا العميل؟',
            'confirm_delete'         => 'هل أنت متأكد من الحذف؟',
            'status_active'          => 'نشط',
            'status_disabled'        => 'معطل',
            'status_pending'         => 'معلق',
            'status_confirmed'       => 'مؤكد',
            'status_completed'       => 'مكتمل',
            'status_cancelled'       => 'ملغي',
            'status_returned'        => 'مرتجع',
            'yes'                    => 'نعم',
            'no'                     => 'لا',

            // Product page
            'view_products'          => 'عرض المنتجات',
            'old_price'              => 'السعر القديم',
            'current_price'          => 'السعر الحالي',
            'quantity'               => 'الكمية',
            'featured'               => 'مميز؟',
            'active_col'             => 'نشط؟',
            'photo'                  => 'الصورة',
            'del_confirm_product'    => 'هل أنت متأكد من حذف هذا المنتج نهائياً؟',
            'del_modal_title'        => 'تأكيد الحذف',
            'del_modal_body'         => 'هل أنت متأكد من حذف هذا العنصر؟',
            'del_modal_warning'      => 'سيتم حذف المنتج نهائياً من قاعدة البيانات.',

            // Employees page
            'view_employees'         => 'إدارة الموظفين',
            'employees_subtitle'     => 'إضافة وتعديل وتعطيل الموظفين وعرض إحصائيات التوزيع.',
            'search_by_name'         => 'بحث بالاسم أو البريد...',
            'auto_assign'            => 'توزيع تلقائي',
            'add_employee'           => 'إضافة موظف',
            'active_employees'       => 'الموظفون النشطون',
            'total_assigned'         => 'إجمالي الطلبات الموزعة',
            'unassigned_orders'      => 'طلبات غير موزعة',
            'full_name_col'          => 'الاسم الكامل',
            'email_col'              => 'البريد الإلكتروني',
            'telegram_status'        => 'حالة التيليجرام',
            'date_added'             => 'تاريخ الإضافة',
            'stats_col'              => 'الإحصائيات',
            'emp_modal_add_title'    => 'إضافة موظف جديد',
            'emp_modal_edit_title'   => 'تعديل بيانات الموظف',
            'full_name_label'        => 'الاسم الكامل',
            'email_label'            => 'البريد الإلكتروني',
            'password_label'         => 'كلمة المرور',
            'password_hint'          => 'اترك فارغاً إن لم ترد التغيير',
            'telegram_label'         => 'معرّف تيليجرام',
            'active_label'           => 'نشط',
            'optional_label'         => 'اختياري',
            'no_employees'           => 'لا يوجد موظفون بعد.',
            'confirm_auto_assign'    => 'توزيع الطلبات غير الموزعة على الموظفين؟',
            'confirm_delete_emp'     => 'هل أنت متأكد؟',
            'test_telegram'          => 'إرسال رسالة اختبار',
        ],

        'fr' => [
            // Navigation / Sidebar
            'nav_home'            => 'Accueil',
            'nav_store_dash'      => 'Tableau boutique',
            'nav_products'        => 'Produits',
            'nav_manage_products' => 'Gérer les produits',
            'nav_top_cat'         => 'Catégories principales',
            'nav_mid_cat'         => 'Sous-catégories',
            'nav_end_cat'         => 'Catégories finales',
            'nav_sizes'           => 'Tailles',
            'nav_colors'          => 'Couleurs',
            'nav_orders'          => 'Commandes',
            'nav_manage_orders'   => 'Gérer les commandes',
            'nav_statistics'      => 'Statistiques',
            'nav_exchange'        => 'Demandes d\'échange',
            'nav_incomplete'      => 'Commandes incomplètes',
            'nav_store'           => 'Boutique',
            'nav_settings'        => 'Paramètres',
            'nav_slider'          => 'Diaporama',
            'nav_countries'       => 'Wilayas / Pays',
            'nav_shipping'        => 'Frais de livraison',
            'nav_people'          => 'Équipe & Personnel',
            'nav_customers'       => 'Clients',
            'nav_employees'       => 'Employés',
            'nav_emp_ranking'     => 'Classement employés',
            'nav_commissions'     => 'Commissions',
            'nav_performance'     => 'Paramètres évaluation',
            'nav_delivery_co'     => 'Transporteurs',
            'nav_events'          => 'Événements & Suivi',
            'nav_event_settings'  => 'Surveillance événements',
            'nav_pixels'          => 'Pixels de suivi',
            'nav_system'          => 'Système',
            'nav_telegram'        => 'Bot Telegram',
            'nav_telegram_dashboard'=> 'Tableau de bord',
            'nav_telegram_settings'=> 'Paramètres du Bot',
            'nav_security'        => 'Sécurité du site',
            'nav_audit'           => 'Journal d\'audit',
            'nav_health'          => 'État du système',
            'nav_ai'              => 'PHI Insights',
            'nav_users'           => 'Gestion des utilisateurs',
            'nav_profile'         => 'Profil',
            'nav_logout'          => 'Déconnexion',
            'nav_control_panel'   => 'Tableau de bord',

            // Common actions
            'add'       => 'Ajouter',
            'edit'      => 'Modifier',
            'delete'    => 'Supprimer',
            'save'      => 'Enregistrer',
            'cancel'    => 'Annuler',
            'search'    => 'Rechercher',
            'actions'   => 'Actions',
            'status'    => 'Statut',
            'date'      => 'Date',
            'name'      => 'Nom',
            'phone'     => 'Téléphone',
            'price'     => 'Prix',
            'quantity'  => 'Quantité',
            'total'     => 'Total',
            'details'   => 'Détails',
            'yes'       => 'Oui',
            'no'        => 'Non',
            'loading'   => 'Chargement...',
            'no_data'   => 'Aucune donnée',
            'all'       => 'Tout',
            'filter'    => 'Filtrer',
            'back'      => 'Retour',
            'view_all'  => 'Voir tout',
            'export'    => 'Exporter',
            'print'     => 'Imprimer',

            // Page titles
            'page_dashboard'      => 'Tableau de bord',
            'page_products'       => 'Gestion des produits',
            'page_orders'         => 'Gestion des commandes',
            'page_customers'      => 'Gestion des clients',
            'page_employees'      => 'Gestion des employés',
            'page_settings'       => 'Paramètres boutique',
            'page_delivery'       => 'Transporteurs',
            'page_billing'        => 'Facturation',
            'page_slider'         => 'Gestion du diaporama',
            'page_categories'     => 'Catégories',
            'page_colors'         => 'Couleurs',
            'page_sizes'          => 'Tailles',
            'page_shipping'       => 'Frais de livraison',
            'page_security'       => 'Sécurité du site',
            'page_audit'          => 'Journal d\'audit',
            'page_health'         => 'État du système',
            'page_users'          => 'Gestion des utilisateurs',
            'page_statistics'     => 'Statistiques',
            'page_commission'     => 'Paramètres des commissions',
            'page_incomplete'     => 'Commandes incomplètes',
            'page_exchange'       => 'Demandes d\'échange',
            'page_pixel'          => 'Pixels de suivi',
            'page_events'         => 'Événements & Suivi',

            // Orders
            'order_id'            => 'N° Commande',
            'order_status'        => 'Statut commande',
            'order_date'          => 'Date commande',
            'order_customer'      => 'Client',
            'order_employee'      => 'Employé',
            'order_delivery'      => 'Livraison',
            'order_product'       => 'Produit',
            'order_value'         => 'Valeur',
            'order_pending'       => 'En attente',
            'order_confirmed'     => 'Confirmée',
            'order_shipped'       => 'Expédiée',
            'order_delivered'     => 'Livrée',
            'order_cancelled'     => 'Annulée',
            'order_returned'      => 'Retournée',
            'add_order'           => 'Ajouter une commande',
            'total_orders'        => 'Total commandes',
            'pending_orders'      => 'Commandes en attente',
            'today_orders'        => 'Commandes du jour',

            // Products
            'product_name'        => 'Nom du produit',
            'product_category'    => 'Catégorie',
            'product_price'       => 'Prix',
            'product_stock'       => 'Stock',
            'product_status'      => 'Statut',
            'product_published'   => 'Publié',
            'product_hidden'      => 'Masqué',
            'add_product'         => 'Ajouter un produit',
            'edit_product'        => 'Modifier le produit',
            'low_stock'           => 'Stock faible',

            // Customers
            'customer_name'       => 'Nom du client',
            'customer_phone'      => 'Téléphone',
            'customer_wilaya'     => 'Wilaya',
            'customer_orders'     => 'Nbre commandes',
            'customer_total'      => 'Total achats',
            'add_customer'        => 'Ajouter un client',

            // Employees
            'employee_name'       => 'Nom de l\'employé',
            'employee_role'       => 'Rôle',
            'employee_orders'     => 'Commandes traitées',
            'employee_commission' => 'Commission',
            'employee_rank'       => 'Classement',

            // Settings
            'store_name'          => 'Nom de la boutique',
            'store_logo'          => 'Logo boutique',
            'store_contact'       => 'Informations de contact',
            'store_social'        => 'Réseaux sociaux',
            'save_settings'       => 'Enregistrer les paramètres',
            'settings_saved'      => 'Paramètres enregistrés avec succès',

            // Common UI
            'num'                    => 'N°',
            'actions'                => 'Actions',
            'delete'                 => 'Supprimer',
            'edit'                   => 'Modifier',
            'save'                   => 'Enregistrer',
            'cancel'                 => 'Annuler',
            'add_btn'                => 'Ajouter',
            'view'                   => 'Voir',
            'search_placeholder'     => 'Rechercher...',
            'account_status'         => 'Statut du compte',
            'full_address'           => 'Adresse complète',
            'change_status'          => 'Changer statut',
            'confirm_delete_customer'=> 'Supprimer ce client ?',
            'confirm_delete'         => 'Confirmer la suppression ?',
            'status_active'          => 'Actif',
            'status_disabled'        => 'Désactivé',
            'status_pending'         => 'En attente',
            'status_confirmed'       => 'Confirmé',
            'status_completed'       => 'Complété',
            'status_cancelled'       => 'Annulé',
            'status_returned'        => 'Retourné',
            'yes'                    => 'Oui',
            'no'                     => 'Non',

            // Product page
            'view_products'          => 'Liste des produits',
            'old_price'              => 'Ancien prix',
            'current_price'          => 'Prix actuel',
            'quantity'               => 'Quantité',
            'featured'               => 'En vedette ?',
            'active_col'             => 'Actif ?',
            'photo'                  => 'Photo',
            'del_confirm_product'    => 'Supprimer ce produit définitivement ?',
            'del_modal_title'        => 'Confirmer la suppression',
            'del_modal_body'         => 'Voulez-vous vraiment supprimer cet élément ?',
            'del_modal_warning'      => 'Ce produit sera définitivement supprimé.',

            // Employees page
            'view_employees'         => 'Gestion des employés',
            'employees_subtitle'     => 'Ajouter, modifier et gérer les employés.',
            'search_by_name'         => 'Rechercher par nom ou email...',
            'auto_assign'            => 'Distribution auto',
            'add_employee'           => 'Ajouter un employé',
            'active_employees'       => 'Employés actifs',
            'total_assigned'         => 'Total commandes assignées',
            'unassigned_orders'      => 'Commandes non assignées',
            'full_name_col'          => 'Nom complet',
            'email_col'              => 'E-mail',
            'telegram_status'        => 'Statut Telegram',
            'date_added'             => "Date d'ajout",
            'stats_col'              => 'Statistiques',
            'emp_modal_add_title'    => 'Ajouter un employé',
            'emp_modal_edit_title'   => "Modifier l'employé",
            'full_name_label'        => 'Nom complet',
            'email_label'            => 'Adresse e-mail',
            'password_label'         => 'Mot de passe',
            'password_hint'          => 'Laisser vide pour ne pas changer',
            'telegram_label'         => 'ID Telegram',
            'active_label'           => 'Actif',
            'optional_label'         => 'Optionnel',
            'no_employees'           => "Aucun employé pour l'instant.",
            'confirm_auto_assign'    => 'Distribuer les commandes non assignées aux employés ?',
            'confirm_delete_emp'     => 'Êtes-vous sûr ?',
            'test_telegram'          => 'Envoyer un message de test',
        ],

        'en' => [
            // Navigation / Sidebar
            'nav_home'            => 'Home',
            'nav_store_dash'      => 'Store Dashboard',
            'nav_products'        => 'Products',
            'nav_manage_products' => 'Manage Products',
            'nav_top_cat'         => 'Main Categories',
            'nav_mid_cat'         => 'Sub-categories',
            'nav_end_cat'         => 'Final Categories',
            'nav_sizes'           => 'Sizes',
            'nav_colors'          => 'Colors',
            'nav_orders'          => 'Orders',
            'nav_manage_orders'   => 'Manage Orders',
            'nav_statistics'      => 'Statistics',
            'nav_exchange'        => 'Exchange Requests',
            'nav_incomplete'      => 'Incomplete Orders',
            'nav_store'           => 'Store',
            'nav_settings'        => 'Settings',
            'nav_slider'          => 'Slider',
            'nav_countries'       => 'States / Countries',
            'nav_shipping'        => 'Shipping Costs',
            'nav_people'          => 'Team & Staff',
            'nav_customers'       => 'Customers',
            'nav_employees'       => 'Employees',
            'nav_emp_ranking'     => 'Employee Ranking',
            'nav_commissions'     => 'Commissions',
            'nav_performance'     => 'Performance Settings',
            'nav_delivery_co'     => 'Delivery Companies',
            'nav_events'          => 'Events & Tracking',
            'nav_event_settings'  => 'Event Monitoring',
            'nav_pixels'          => 'Tracking Pixels',
            'nav_system'          => 'System',
            'nav_telegram'        => 'Telegram Bot',
            'nav_telegram_dashboard'=> 'Dashboard',
            'nav_telegram_settings'=> 'Bot Settings',
            'nav_security'        => 'Site Security',
            'nav_audit'           => 'Audit Log',
            'nav_health'          => 'System Health',
            'nav_ai'              => 'PHI Insights',
            'nav_users'           => 'User Management',
            'nav_profile'         => 'Profile',
            'nav_logout'          => 'Logout',
            'nav_control_panel'   => 'Control Panel',

            // Common actions
            'add'       => 'Add',
            'edit'      => 'Edit',
            'delete'    => 'Delete',
            'save'      => 'Save',
            'cancel'    => 'Cancel',
            'search'    => 'Search',
            'actions'   => 'Actions',
            'status'    => 'Status',
            'date'      => 'Date',
            'name'      => 'Name',
            'phone'     => 'Phone',
            'price'     => 'Price',
            'quantity'  => 'Qty',
            'total'     => 'Total',
            'details'   => 'Details',
            'yes'       => 'Yes',
            'no'        => 'No',
            'loading'   => 'Loading...',
            'no_data'   => 'No data',
            'all'       => 'All',
            'filter'    => 'Filter',
            'back'      => 'Back',
            'view_all'  => 'View All',
            'export'    => 'Export',
            'print'     => 'Print',

            // Page titles
            'page_dashboard'      => 'Admin Dashboard',
            'page_products'       => 'Product Management',
            'page_orders'         => 'Order Management',
            'page_customers'      => 'Customer Management',
            'page_employees'      => 'Employee Management',
            'page_settings'       => 'Store Settings',
            'page_delivery'       => 'Delivery Companies',
            'page_billing'        => 'Billing',
            'page_slider'         => 'Slider Management',
            'page_categories'     => 'Categories',
            'page_colors'         => 'Colors',
            'page_sizes'          => 'Sizes',
            'page_shipping'       => 'Shipping Costs',
            'page_security'       => 'Site Security',
            'page_audit'          => 'Audit Log',
            'page_health'         => 'System Health',
            'page_users'          => 'User Management',
            'page_statistics'     => 'Statistics',
            'page_commission'     => 'Commission Settings',
            'page_incomplete'     => 'Incomplete Orders',
            'page_exchange'       => 'Exchange Requests',
            'page_pixel'          => 'Tracking Pixels',
            'page_events'         => 'Events & Tracking',

            // Orders
            'order_id'            => 'Order #',
            'order_status'        => 'Order Status',
            'order_date'          => 'Order Date',
            'order_customer'      => 'Customer',
            'order_employee'      => 'Employee',
            'order_delivery'      => 'Delivery',
            'order_product'       => 'Product',
            'order_value'         => 'Value',
            'order_pending'       => 'Pending',
            'order_confirmed'     => 'Confirmed',
            'order_shipped'       => 'Shipped',
            'order_delivered'     => 'Delivered',
            'order_cancelled'     => 'Cancelled',
            'order_returned'      => 'Returned',
            'add_order'           => 'Add Order',
            'total_orders'        => 'Total Orders',
            'pending_orders'      => 'Pending Orders',
            'today_orders'        => 'Today\'s Orders',

            // Products
            'product_name'        => 'Product Name',
            'product_category'    => 'Category',
            'product_price'       => 'Price',
            'product_stock'       => 'Stock',
            'product_status'      => 'Status',
            'product_published'   => 'Published',
            'product_hidden'      => 'Hidden',
            'add_product'         => 'Add Product',
            'edit_product'        => 'Edit Product',
            'low_stock'           => 'Low Stock',

            // Customers
            'customer_name'       => 'Customer Name',
            'customer_phone'      => 'Phone',
            'customer_wilaya'     => 'State',
            'customer_orders'     => 'Orders Count',
            'customer_total'      => 'Total Purchases',
            'add_customer'        => 'Add Customer',

            // Employees
            'employee_name'       => 'Employee Name',
            'employee_role'       => 'Role',
            'employee_orders'     => 'Completed Orders',
            'employee_commission' => 'Commission',
            'employee_rank'       => 'Rank',

            // Settings
            'store_name'          => 'Store Name',
            'store_logo'          => 'Store Logo',
            'store_contact'       => 'Contact Information',
            'store_social'        => 'Social Media',
            'save_settings'       => 'Save Settings',
            'settings_saved'      => 'Settings saved successfully',

            // Common UI
            'num'                    => '#',
            'actions'                => 'Actions',
            'delete'                 => 'Delete',
            'edit'                   => 'Edit',
            'save'                   => 'Save',
            'cancel'                 => 'Cancel',
            'add_btn'                => 'Add',
            'view'                   => 'View',
            'search_placeholder'     => 'Search...',
            'account_status'         => 'Account Status',
            'full_address'           => 'Full Address',
            'change_status'          => 'Change Status',
            'confirm_delete_customer'=> 'Delete this customer?',
            'confirm_delete'         => 'Confirm deletion?',
            'status_active'          => 'Active',
            'status_disabled'        => 'Disabled',
            'status_pending'         => 'Pending',
            'status_confirmed'       => 'Confirmed',
            'status_completed'       => 'Completed',
            'status_cancelled'       => 'Cancelled',
            'status_returned'        => 'Returned',
            'yes'                    => 'Yes',
            'no'                     => 'No',

            // Product page
            'view_products'          => 'Product List',
            'old_price'              => 'Old Price',
            'current_price'          => 'Current Price',
            'quantity'               => 'Qty',
            'featured'               => 'Featured?',
            'active_col'             => 'Active?',
            'photo'                  => 'Photo',
            'del_confirm_product'    => 'Delete this product permanently?',
            'del_modal_title'        => 'Delete Confirmation',
            'del_modal_body'         => 'Are you sure you want to delete this item?',
            'del_modal_warning'      => 'This product will be permanently deleted.',

            // Employees page
            'view_employees'         => 'Employee Management',
            'employees_subtitle'     => 'Add, edit and manage employees.',
            'search_by_name'         => 'Search by name or email...',
            'auto_assign'            => 'Auto Assign',
            'add_employee'           => 'Add Employee',
            'active_employees'       => 'Active Employees',
            'total_assigned'         => 'Total Assigned Orders',
            'unassigned_orders'      => 'Unassigned Orders',
            'full_name_col'          => 'Full Name',
            'email_col'              => 'Email',
            'telegram_status'        => 'Telegram Status',
            'date_added'             => 'Date Added',
            'stats_col'              => 'Statistics',
            'emp_modal_add_title'    => 'Add Employee',
            'emp_modal_edit_title'   => 'Edit Employee',
            'full_name_label'        => 'Full Name',
            'email_label'            => 'Email Address',
            'password_label'         => 'Password',
            'password_hint'          => 'Leave blank to keep current',
            'telegram_label'         => 'Telegram ID',
            'active_label'           => 'Active',
            'optional_label'         => 'Optional',
            'no_employees'           => 'No employees yet.',
            'confirm_auto_assign'    => 'Distribute unassigned orders to employees?',
            'confirm_delete_emp'     => 'Are you sure?',
            'test_telegram'          => 'Send test message',
        ],
    ];

    return $strings[$lang] ?? $strings['ar'];
}

/**
 * Shorthand: get one translation string
 */
function __t(string $key, string $lang = '', string $default = ''): string {
    static $cache = [];
    if (!$lang) {
        $lang = $_SESSION['admin_lang'] ?? 'ar';
    }
    if (!isset($cache[$lang])) {
        $cache[$lang] = get_lang_strings($lang);
    }
    return $cache[$lang][$key] ?? $default ?: $key;
}
